### ISSUE TITLE
[Bug] Matrix Blank folder after backing up 

### ISSUE THREAD

**Issue by Blurayx** [marcelveldt/script.skin.helper.skinbackup#14]
Blank folder after backing up

[kodi.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6097158/kodi.log)

"Backupfile was successfully created"
<img width="1603" alt="Screenshot 2021-03-07 at 12 49 08" src="https://user-images.githubusercontent.com/2873112/110240929-1879b600-7f46-11eb-8fc7-66bcf788ad65.png">

 Blank folder after backing up
<img width="1603" alt="Screenshot 2021-03-07 at 12 49 23" src="https://user-images.githubusercontent.com/2873112/110240960-44953700-7f46-11eb-9a66-8346941615c4.png">

Thanks

**Comment by Blurayx** [comment]
Hi,

Has this project been abandoned?

Thanks

**Comment by Angelinas1** [comment]
In your log you use script.skin.helper.skinbackup v1.0.28 installed
Please use from this site
https://github.com/kodi-community-addons/script.skin.helper.skinbackup/archive/refs/heads/master.zip
now is for Matrix version="1.0.19"

**Comment by Blurayx** [comment]
I previously tried version 1.0.19. Unfortunately, 1.0.19. is worse because nothing happens when I click on backup. Also, there's no image for the icon

[kodi.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6175532/kodi.log)



https://user-images.githubusercontent.com/2873112/111869548-fe919780-8977-11eb-8cb4-32f109681702.mp4

**Comment by Angelinas1** [comment]
Latest changes, test please
https://github.com/kodi-community-addons/script.skin.helper.skinbackup/commit/c671440fcd714ef63aaba0304ca293d2c51dc2fe

**Comment by Blurayx** [comment]
It only backs-up on the first install. after that all backups fail.

[kodi.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6175950/kodi.log)



https://user-images.githubusercontent.com/2873112/111876597-51c71280-8997-11eb-955b-14e3ca4ab658.mp4

Thanks for your patients 🙂

**Comment by Angelinas1** [comment]
that is ok....name was change in skin name + only date....you try in same day......Owerwrite your file if you try in same date :)

**Comment by Blurayx** [comment]
ok, that worked. The Kodi 18 version created its own individual time stamp. Now I have another issue. it's not restoring my sub-menu settings.

[kodi.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6176166/kodi.log)

Sub-menu: "30 minute workouts"



https://user-images.githubusercontent.com/2873112/111881831-50531580-89aa-11eb-9605-54227ced1e18.mp4

Thanks

**Comment by Angelinas1** [comment]
I see on your video(images-video tell more then word) :)
 .....problem with script.skinshortcuts backup.
Mine Aeonmq6 doesen't use script.skinshortcuts, and backup work for me.Tomorow I will try to fix that part too.

**Comment by Blurayx** [comment]
Thanks😀

**Comment by Angelinas1** [comment]
Blurayx,  some missing part....new version is available version="1.0.20" 
Please test

**Comment by Blurayx** [comment]
The multiple backups work great but for restoring the Artic horizon submenu and widgets still not working.
[kodi.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6177429/kodi.log)
[kodi old.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6177430/kodi.old.log)


https://user-images.githubusercontent.com/2873112/111906412-64e5eb00-8a48-11eb-974a-fb0678ee61f0.mp4

Thanks

**Comment by Angelinas1** [comment]
I think skinshortcuts works when you change some code write as hah.Script backup only backup that changes, doesent have start for skin setings in skin folder.
If you restore menu items in skin and then start restore all your changes will be restored ?!?

**Comment by Blurayx** [comment]
"If you restore menu items in skin and then start restore all your changes will be restored ?!?"

sorry, I'm a bit confused with the question.

**Comment by Blurayx** [comment]
Update: performed a clean install then restored from skin backup. As you can see nothing has been saved correctly compared to my original settings. https://github.com/kodi-community-addons/script.skin.helper.skinbackup/issues/14#issuecomment-803578937

[kodi.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6178409/kodi.log)
[kodi.old.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6178410/kodi.old.log)

It saved my sub-menus and widgets but not on the home screen. You can see my original configurations in the skin settings.


https://user-images.githubusercontent.com/2873112/111921158-eb232100-8a8a-11eb-8880-487e7282b192.mp4

Thanks

**Comment by Angelinas1** [comment]
Create backup before this action
-Try to add, music widget in tv show,..... you always delete widget...
-Change position tvshow and movie in home screen
-Change orientation from verical to horisontal 
go to home screen to force script.skinshortcuts to write changes in his addon_data/script.skinshortcuts folder
you have home like this
https://i.imgur.com/R5cQp4u.png
now is time to restore...
When you back to home only orientation is back(that is from skinsetings.xml)
but if you go to skin setings you will see that all changes are back.only script.skinshortcuts didnt start to change.
I dont know how to find button to reload skin, but I triger script.skinshortcuts with changing order of movie widget to force to reload script.skinshortcuts.
And finaly go to Home......all is back

try this

**Comment by Blurayx** [comment]
After a restore,  the submenus still missing. The music widgets remain on the home screen but are not in the skin settings.
[kodi.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6178569/kodi.log)
[kodi.old.log](https://github.com/kodi-community-addons/script.skin.helper.skinbackup/files/6178571/kodi.old.log)


https://user-images.githubusercontent.com/2873112/111924246-6a205580-8a9b-11eb-84b8-aadd4aad7056.mp4

After skin backup restore:

Submenu settings do not show on the home screen if they are deleted before the restore.
<img width="1264" alt="Screenshot 2021-03-21 at 23 04 03" src="https://user-images.githubusercontent.com/2873112/111924262-7d332580-8a9b-11eb-9655-f736be0204e8.png">

No music widgets configured but still remain on the home screen
<img width="1264" alt="Screenshot 2021-03-21 at 23 06 55" src="https://user-images.githubusercontent.com/2873112/111924324-d8651800-8a9b-11eb-9872-0f590ce4a333.png">


Thanks

**Comment by Angelinas1** [comment]
OK reload skin dosen't triger script.skinshortcuts to write changes.
But if you change order of widget in movie, and back to home will....need to have icon on home in right corner.

**Comment by Blurayx** [comment]
Thanks for your patience & hard work but I think I'm going to give up on Skin backup. I have found an alternative, using backup. 
Over the years I haven't had any issue with skin backup until python 3 came along 🙂

I can leave you in peace now lol

Backup
<img width="1176" alt="Screenshot 2021-03-22 at 16 56 13" src="https://user-images.githubusercontent.com/2873112/112028903-9639e600-8b30-11eb-9ae6-7d9cd453043f.png">

Setting to fully restore Arctic Horizon 
<img width="1068" alt="Screenshot 2021-03-22 at 16 55 52" src="https://user-images.githubusercontent.com/2873112/112029051-bec1e000-8b30-11eb-8123-358a3aacab3a.png">
