### ISSUE TITLE
issue with promptfilename=true

### ISSUE THREAD

**Issue by sualfred** [marcelveldt/script.skin.helper.skinbackup#6]
Hey Marcel,

If the backup is script is started with the promptfilename argument, it will prefill the edit field with the set storage path and the common user will add his file name next to the path. The problem is.... that is going to break the backup :) You'll get a success message but the file cannot be created. 

Edit:
I also miss a option the manually choose the path for each backup.

**Comment by marcelveldt** [comment]
Issue will be fixed in next update, thanks.
As for the backup path, it will use the path that is set in the addon's settings.
